### PR TITLE
Shops CRUD

### LINKED ISSUE #9: US_shops#index
User can see all shops

### LINKED ISSUE #10: US_shops#show
User can see shop info, access to shop website, and call shop (optional)

### LINKED ISSUE #11: US_shops#new-create
User can add a new shop

### LINKED ISSUE #12: US_shops#edit-update
User can edit a shop

### LINKED ISSUE #49: Seed not working
## Raised Error

image
### Logic causing this error

image

### PR DESCRIPTION
**Pull request by sbriclot**
* Add a column Closed in the table Shops
* Create the Shops index :
    - by default, display only the non-closed shops
    - use the checkbox to display/hide closed shops
    - Home/Booking links displayed only if an URL exists
    - a tag Closed is displayed for closed shops. Have to look how to display it as a watermark on the shop card
* Create the New/Edit mask :
    - the field Closed is displayed in Edit mode only
    - for the moment, only the name is mandatory
    - phone number is checked by a regex (numbers only, with an optional prepending + for international format)
    - URLs are checked by regex, must start with www or http
    - if an URL doesn't start with http or https, http:// is added before save (a full URL is mandatory to be usable with the tag link_to)

Show is not created for the moment, not sure we need one.
Delete is useless, a shop can be flagged as Closed, but not deleted.

### CODE REVIEW

File: app/models/shop.rb [hunk 1]
```diff
@@ -1,3 +1,24 @@
...
+
+  private
+  def format_url
+    p self
+    if self.home_url.length > 0
+      unless home_url[/\Ahttp:\/\//] || home_url[/\Ahttps:\/\//]
+        self.home_url = "http://#{home_url}"
+      end
+    end
+    if self.booking_url.length > 0
```
Comment (JPS09) [inline app/models/shop.rb:18]: This logic breaks the seed, see #49 for details.

File: app/models/shop.rb [hunk 2]
```diff
@@ -1,3 +1,24 @@
...
+      unless booking_url[/\Ahttp:\/\//] || booking_url[/\Ahttps:\/\//]
+        self.booking_url = "http://#{booking_url}"
+      end
+    end
+  end
 end
```
Comment (JPS09) [inline app/models/shop.rb]: This logic breaks the seed, see #49 for details.

**Review by JPS09 — CHANGES_REQUESTED** [review]

**Comment by sbriclot** [comment]
Bug fixed :
- Change the logic in the model to manage nil OR empty urls.
- Change the logic in the index page to manage nil OR empty urls.
- Change seed file to manage each cases (valid/invalid URL, empty string, NULL value).
- Add a validation rule to the model to format phone number (remove everything except + and numbers before validation).
- Fix a syntax issue in the controller (Rubocop cleaning).

File: app/models/shop.rb (hunk 2 above)
Comment (sbriclot) [reply app/models/shop.rb]: Changes done, see the last commit.

**Review by Mordhin — APPROVED** [review]

File: app/views/shops/index.html.erb [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+      <% unless shop.home_url.nil? %>
+        <% unless shop.home_url.empty? %>
+          <%= link_to "Home", shop.home_url, :target => "_blank" %>
+        <% end %>
+      <% end %>
+      <% unless shop.booking_url.nil? %>
+        <% unless shop.booking_url.empty? %>
+          <%= link_to "Booking", shop.booking_url, :target => "_blank" %>
+        <% end %>
+      <% end %>
```
Comment (JPS09) [inline app/views/shops/index.html.erb]: Could this work ?
```suggestion
      <% unless shop.home_url.nil?  ||  shop.home_url.empty? %>
           <%= link_to "Home", shop.home_url, :target => "_blank" %>
        <% end %>
      <% unless shop.booking_url.nil? || shop.booking_url.empty?  %>
           <%= link_to "Booking", shop.booking_url, :target => "_blank" %>
        <% end %>
    
```

**Review by JPS09 — APPROVED** [review]
Good for me, good work !

File: app/views/shops/index.html.erb (hunk 3 above)
Comment (sbriclot) [reply app/views/shops/index.html.erb]: Strange, I tested this syntax this morning but it failed, empty? was tested in each case and raised an error when the URL was NIL. (even if normally, when the first condition is FALSE, the second is supposed to be skipped.
I had the same problem in the model validation.

But I tried to reproduce the case now to catch the error message and it's working 
I don't know why I have a different result now. I use a new server session, but this can explain the problem with the view only, not with the model.
And I had to restart my WSL tonight (wsl --shutdown), but I don't know if this can be an explanation.

Anyway, I changed the UNLESS  conditions in model and view, it's better.
